var lstMail;var lstSock;var chkEmail;var chkBank;var chkCard;var chkInfo;var chkChange;var maxFail;var delim;var timeout;var WRONG_FORMAT=-1;var SOCK_DIE=1;var ACC_DIE=2;var ACC_LIVE=0;var docTitle=document.title;$.xhrPool=[];$.xhrPool.abortAll=function(){$(this).each(function(idx,jqXHR){jqXHR.abort();});$.xhrPool.length=0};$.fn.showLoading=function(msg){msg=msg||'';$(this).html('<img src="'+ SITE_URL+'/style/img/loading.gif"> '+ msg).show();}
$.fn.hideLoading=function(){$(this).hide();}
$.ajaxSetup({beforeSend:function(jqXHR){$.xhrPool.push(jqXHR);},complete:function(jqXHR){var index=$.xhrPool.indexOf(jqXHR);if(index>-1){$.xhrPool.splice(index,1);}}});Array.prototype.remove=function(value){var index=this.indexOf(value);if(index!=-1){this.splice(index,1);}
return this;};function setInputEnable(bool){$('#socks').attr('disabled',bool);$('#mailpass').attr('disabled',bool);}
function up(obj){var count=parseInt($(obj).text());count++;$(obj).text(count);}
function stopLoading(bool){setInputEnable(false);$('#submit').removeClass('disabled').attr('disabled',false);$('#stop').addClass('disabled').attr('disabled',true);$('#loading').hideLoading();$('.progress').removeClass('active');$.xhrPool.abortAll();document.title='STOPPED '+ document.title;if(bool){$('#alert').modal('show');}}
function isEmail(str){var re=/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;return re.test(str);}
function updateProgress(current,total){$('.check-amount').text('Progress: '+current+'/'+ total);var percent=Math.floor((current/total)*100);$('.progress-bar').css('width',percent+'%').attr('aria-valuenow',percent);$('.progress-text').text(percent+'%');document.title=percent+'% ['+current+'/'+ total+'] '+ docTitle;}
function resetResult(){$('#socks-die,#acc-die,#wrong-format').html('');$('.socks-die,.acc-die,.wrong-format').text('0');}
function updateTextBox(mp,sock){if(mp.length>0){var mailpass=$('#mailpass').val().split("\n");mailpass.remove(mp);$('#mailpass').val(mailpass.join("\n"));}
if(sock.length>0){var socks=$('#socks').val().split("\n");socks.remove(sock);$('#socks').val(socks.join("\n"));}}
$(document).ready(function(){$('#stop').addClass('disabled').attr('disabled',true).click(function(){stopLoading(false);});$('.remove-limited').css('cursor','pointer').click(function(){$('.limited').parent().fadeIn(100,function(){$(this).remove();})});$('.import-sock').click(function(){$.ajax({url:SOCK_URL,dataType:'json',type:'POST',data:'ajax=1&delim=0&mailpass=v3ch4j',success:function(data){var socks=data.socks;$('#socks').val(socks.replace(/\,/g,"\n"));},error:function(data,status,error){if(status=='error'){alert('Error! Please try again or contact admin');}}})});});